### ISSUE TITLE
ITEM_LOGIN_REQUIRED error

### ISSUE THREAD

**Issue by timtraversy** [bencooper222/build-your-own-mint#22]
Linked a Capital One account with `npm run token-plaid`.

When I run `npm run test-plaid` I get this error:

```
{
   "account":"capital-one",
   "err":{
      "name":"PlaidError",
      "display_message":null,
      "error_code":"ITEM_LOGIN_REQUIRED",
      "error_message":"the login details of this item have changed (credentials, MFA, or required user action) and a user login is required to update this information. use Link's update mode to restore the item to a good state",
      "error_type":"ITEM_ERROR",
      "request_id":"QIb92hjj2B8tOaX",
      "suggested_action":null,
      "status_code":400
   }
}
```

Just wondering if anyone has seen this before. Error message points to [these docs](https://plaid.com/docs/#updating-items-via-link)

**Comment by bencooper222** [comment]
I’ll try and take a look later today. This is a common issue that I’ve had with Barclays bank that just kinda goes away after a while. That said, I haven’t tried the test-plaid command in a while so it’s possible the problem is there. I’d be vaguely surprised if this happened to cap one since they’re a big bank and a pretty tech forward one. 

Also note that a LOT of stuff has changed since the README was updated. I’ve been meaning to update it - I’ll go ahead and do that as well.

**Comment by timtraversy** [comment]
Thanks @bencooper222. I think C1 tightened up API security after the security breach last year, Plaid used to have issues with them and even [Mint doesn't have full access.](https://help.mint.com/Featured-Questions/1103430161/Capital-One-transactions-are-missing-or-not-downloaded.htm).

**Comment by timtraversy** [comment]
Related: https://stackoverflow.com/questions/58674564/plaid-only-giving-item-login-required-for-capital-one

**Comment by timtraversy** [comment]
Closing this because it's not on your end.

**Comment by bencooper222** [comment]
FWIW, you can view institution status here: https://dashboard.plaid.com/activity/status/institution/ins_9

(might have to be logged into plaid)

**Comment by timtraversy** [comment]
Oh neat. Too bad there’s no communication about when it will be resolved.
